### PR TITLE
Feature/add cart redux

### PR DESCRIPTION
**Pull request by aadarsh10c**
It took long , but i have completed the all the task mentioned in the issue #7 ,  I have added some helpful comments, but let me know , if u have any doubts and need improvements. Also I have added 2 react components for cart  and a button .

I have added a basic working cart , it will certainly require some styling and minor improvements.

### CODE REVIEW

**Comment by mohammadruman** [comment]
We have merged the PR, but there's an issue with your code. Could you check if it's running properly? There's also a problem with rendering the food court menu after this merge.

**Comment by mohammadruman** [comment]
Could you please send a new pull request with a screenshot of the working UI? of cart component

**Comment by mohammadruman** [comment]
> Could you please send a new pull request with a screenshot of the working UI? of cart component

We are facing some issues on our end sorry for the inconvenience

**Comment by aadarsh10c** [comment]
> > Could you please send a new pull request with a screenshot of the working UI? of cart component
> 
> We are facing some issues on our end sorry for the inconvenience

@mohammadruman ,  Sorry for the late response , Its working fine for i will send you a screen shot . Please lte me knwo what the issue is , additonaly , i added a pacakge redux-persist which saves data , which can be retrived later page is refreshed. so may be try npm i in forntend directory

**Pull request merged**
